#ifndef BOARD_E87_1542_FULL_CFG_H
#define BOARD_E87_1542_FULL_CFG_H

#undef TCFG_DEBUG_UART_ENABLE
#define TCFG_DEBUG_UART_ENABLE 0
#undef TCFG_APP_BT_EN
#define TCFG_APP_BT_EN 0
#undef TCFG_USER_BLE_ENABLE
#define TCFG_USER_BLE_ENABLE 0
#undef TCFG_USER_BT_CLASSIC_ENABLE
#define TCFG_USER_BT_CLASSIC_ENABLE 0
#undef TCFG_USER_TWS_ENABLE
#define TCFG_USER_TWS_ENABLE 0
#undef TCFG_BT_AI_ENABLE
#define TCFG_BT_AI_ENABLE 0
#undef TCFG_BT_BACKGROUND_ENABLE
#define TCFG_BT_BACKGROUND_ENABLE 0
#undef TCFG_NORMAL_SET_DUT_MODE
#define TCFG_NORMAL_SET_DUT_MODE 0
#undef TCFG_AUTO_POWERON_ENABLE
#define TCFG_AUTO_POWERON_ENABLE 1
#undef WDT_APP_INIT_TIME
#define WDT_APP_INIT_TIME WDT_16S
#undef WDT_APP_RUN_TIME
#define WDT_APP_RUN_TIME WDT_LRC_4S
#undef TCFG_UI_ENABLE
#define TCFG_UI_ENABLE 0
#undef CONFIG_JL_UI_ENABLE
#define CONFIG_JL_UI_ENABLE 0
#undef CONFIG_LVGL_UI_ENABLE
#define CONFIG_LVGL_UI_ENABLE 0
#undef TCFG_TOUCH_PANEL_ENABLE
#define TCFG_TOUCH_PANEL_ENABLE 0
#undef TCFG_ADKEY_ENABLE
#define TCFG_ADKEY_ENABLE 0
#undef TCFG_IOKEY_ENABLE
#define TCFG_IOKEY_ENABLE 0
#undef TCFG_RDEC_KEY_ENABLE
#define TCFG_RDEC_KEY_ENABLE 0
#undef TCFG_CHARGE_ENABLE
#define TCFG_CHARGE_ENABLE 0
#undef TCFG_UPDATE_ENABLE
#define TCFG_UPDATE_ENABLE 0
#undef TCFG_CFG_TOOL_ENABLE
#define TCFG_CFG_TOOL_ENABLE 0
#undef PRODUCT_TEST_ENABLE
#define PRODUCT_TEST_ENABLE 0
#undef TCFG_PSRAM_DEV_ENABLE
#define TCFG_PSRAM_DEV_ENABLE 0
#undef CONFIG_LCD_BUF_STATIC_RAM_LEN
#define CONFIG_LCD_BUF_STATIC_RAM_LEN 0x6000
#define E87_FULL_LCD_BUFFER_BYTES 0x5460

#endif
